# Generated by Django 3.2.7 on 2025-06-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('code', models.IntegerField(unique=True)),
                ('directions', models.JSONField(default=list)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('charger', models.BooleanField(default=False)),
                ('chute', models.BooleanField(default=False)),
            ],
        ),
    ]
