# Generated by Django 4.2.23 on 2025-06-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='charger',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='chute',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
